apiVersion: skaffold/v3
kind: Config
profiles:
- name: dev
  activation:
  - env: REF_BRANCH=dev
  # - kubeContext: dewacloud-cluster
  build:
    tagPolicy:
      envTemplate:
        template: "dev-{{.TAGS}}"
    artifacts:
    - image: python-server
      context: ./app-1
      docker:
        dockerfile: Dockerfile

  manifests:
    rawYaml:
    - k8s/dev/*.yaml

- name: stag
  activation:
  - env: REF_BRANCH=master
  # - kubeContext: aws-cluster
  manifests:
    rawYaml:
    - k8s/stag/*.yaml
  build:
    tagPolicy:
      envTemplate:
        template: "stag-{{.TAGS}}"
    artifacts:
    - image: python-server
      context: ./app-1
      docker:
        dockerfile: Dockerfile
