FROM python:3.11-slim-bookworm AS base
# Install system packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    supervisor git \
    && rm -rf /var/lib/apt/lists/*
COPY --from=ghcr.io/astral-sh/uv:0.4.30 /uv /uvx /bin/
