name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Skaffold
      uses: GoogleContainerTools/skaffold@v2

    - name: Build and push Docker image
      run: skaffold build --file-output=build.out

    - name: Push Docker image to GitHub Container Registry
      run: docker push ${{ env.IMAGE_NAME }}
